app:
  name: app
  verstion: 1.0.0
  env: production

data: 
  processed_dir: data/processed
  raw_dir: data/raw

# setting env
api_key:
  unstructured_api_key:
  llamaindex_api:

embedding:
  model:
  device: cpu
  batch_size: 64

chunking:
  size:



llm:
  model_name: "Qwen/Qwen2-VL-2B-Instruct" # Example model, can be changed
  device: "cuda" # or "cpu"
  max_new_tokens: 512
  temperature: 0.1
  top_p: 0.9
  load_in_4bit: true

vector_database:
  type: qdrant
  host: localhost
  port: 6333
  url: http://localhost:6333  
  api_key: null               
  collection_name: nmk_chatbot_collection
  distance: cosine           
  vector_size: 384
  timeout: 30                

retrieval:
  top_k: 7
  beta: 0.6
  dense_threshhold: 0.4
  reranker:
    enabled: true
    model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    top_n: 5

